import { describe, expect, test } from "bun:test";
import { adaptKevRequest, adaptKevResponse } from "../src/kev.ts";
import { type EntryType, type SystemOneRequest, type SystemOneResponse } from "../src/protocol.ts";
import { validateResponseForRequest } from "../src/response.ts";

const choiceRequest: SystemOneRequest = {
  model: "kev-latest",
  state: null,
  questions: { q: { type: "choice", criteria: { first: null, second: null, third: null } } },
};

function choiceResponse(): SystemOneResponse {
  return {
    model: "kev-latest",
    answers: {
      q: { type: "choice", choice: "first", probabilities: { first: 0.33, second: 0.33, third: 0.33 }, confidence: 0 },
    },
    usage: { input_tokens: 42, output_tokens: 17 },
  };
}

function scorePair(criteria: EntryType[], legend: Record<string, EntryType>): {
  request: SystemOneRequest;
  response: SystemOneResponse;
} {
  return {
    request: { model: "kev-latest", state: null, questions: { q: { type: "score", criteria } } },
    response: {
      model: "kev-latest",
      answers: { q: { type: "score", score: 1, legend, probabilities: { "0": 0.33, "1": 0.33, "2": 0.33 }, confidence: 0.5 } },
      usage: { input_tokens: 42, output_tokens: 17 },
    },
  };
}

describe("Kev protocol adapter", () => {
  test("supplies omitted instructions for every question type in a fresh request", () => {
    const request: SystemOneRequest = {
      state: { message: ["do not mutate"] },
      questions: {
        binary: { type: "noul" },
        pick: { type: "choice", criteria: { yes: null } },
        level: { type: "score", criteria: [null, "high"] },
        explicit: { type: "noul", instructions: "", criteria: null },
        structured: { type: "choice", instructions: { policy: ["keep"] }, criteria: { yes: "Yes" } },
      },
    };
    const before = structuredClone(request);
    const adapted = adaptKevRequest(request);
    expect(adapted).not.toBe(request);
    expect(adapted.questions.binary?.instructions).toBeNull();
    expect(adapted.questions.pick?.instructions).toBeNull();
    expect(adapted.questions.level?.instructions).toBeNull();
    expect(adapted.questions.explicit?.instructions).toBe("");
    expect(adapted.questions.structured?.instructions).toEqual({ policy: ["keep"] });
    expect(adapted.model).toBeUndefined();
    expect(adapted.state).not.toBe(request.state);
    adapted.questions.level!.instructions = "changed";
    expect(request).toEqual(before);
  });

  test("preserves native rounded thirds, selected choice, confidence, and usage", () => {
    const raw = choiceResponse();
    const result = adaptKevResponse(choiceRequest, raw);
    expect(result).toEqual(raw);
    expect(result).not.toBe(raw);
    expect(() => validateResponseForRequest(choiceRequest, raw)).toThrow("Invalid or mismatched");
  });

  test("accepts the native weighted score without renormalizing probabilities", () => {
    const { request, response } = scorePair(["low", "medium", "high"], { "0": "low", "1": "medium", "2": "high" });
    expect(adaptKevResponse(request, response)).toEqual(response);
    expect(() => validateResponseForRequest(request, response)).toThrow("Invalid or mismatched");
  });

  test("restores original null, object, and nested list legends after verifying native rendering", () => {
    // Legends generated by render() from pinned kev/api.py e943f21e40574d99cefb2d292089333bcda9047c.
    const structured: EntryType = { enabled: true, nested: [false, null, { reason: "yes", levels: [1, 0.00001, 1e-7] }] };
    const list: EntryType = ["  first", [" next", false], "\u0085trim", "\ufeffkeep"];
    const { request, response } = scorePair([null, structured, list], {
      "0": "",
      "1": "enabled: True\nnested:\n  - False\n  - \n  - reason: yes\n    levels:\n      - 1\n      - 1e-05\n      - 1e-07",
      "2": "- first\n- - next\n  - False\n- trim\n- \ufeffkeep",
    });
    const beforeRequest = structuredClone(request);
    const beforeResponse = structuredClone(response);
    const result = adaptKevResponse(request, response);
    const answer = result.answers.q;
    expect(answer?.type).toBe("score");
    if (answer?.type !== "score") throw new Error("Expected score");
    expect(answer.legend).toEqual({ "0": null, "1": structured, "2": list });
    expect(answer.legend["1"]).not.toBe(structured);
    expect(answer.probabilities).toEqual({ "0": 0.33, "1": 0.33, "2": 0.33 });
    expect(request).toEqual(beforeRequest);
    expect(response).toEqual(beforeResponse);
  });

  test("matches Python rendering of numbers as received over JSON", () => {
    const criterion = { tiny: 0.00001, small: 0.0001, big: 1e21, integer: 100000000000000000000, minus: -0 };
    const { request, response } = scorePair([null, criterion, "high"], {
      "0": "",
      "1": "tiny: 1e-05\nsmall: 0.0001\nbig: 1e+21\ninteger: 100000000000000000000\nminus: 0",
      "2": "high",
    });
    expect(adaptKevResponse(request, response).answers.q).toMatchObject({ legend: { "1": criterion } });
  });

  test("rejects changed native legends instead of covering the mismatch with request entries", () => {
    const { request, response } = scorePair([null, { enabled: true }, "high"], { "0": "", "1": "enabled: True", "2": "high" });
    for (const wrong of ["enabled: False", "enabled: true", { enabled: true }, null]) {
      const invalid = structuredClone(response);
      if (invalid.answers.q?.type !== "score") throw new Error("Expected score");
      invalid.answers.q.legend["1"] = wrong;
      expect(() => adaptKevResponse(request, invalid)).toThrow("Invalid or mismatched");
    }
  });

  test("accepts native Noul and unpinned model identity, rejects a mismatched pinned model", () => {
    const request: SystemOneRequest = { state: null, questions: { q: { type: "noul" } } };
    const response: SystemOneResponse = { model: "kev-latest", answers: { q: { type: "noul", noul: 0.67 } }, usage: { input_tokens: 2, output_tokens: 3 } };
    expect(adaptKevResponse(request, { ...response, latency_ms: 10 })).toEqual(response);
    expect(() => adaptKevResponse({ ...request, model: "different" }, response)).toThrow("Invalid or mismatched");
  });

  test("rejects malformed responses, unknown questions or options, and inconsistent choices", () => {
    const invalid: unknown[] = [null, {}, { ...choiceResponse(), model: "other" }, { ...choiceResponse(), usage: { input_tokens: -1, output_tokens: 0 } }];
    for (const change of [
      { probabilities: { first: 0.5, second: 0.5 } },
      { probabilities: { first: 0.33, second: 0.33, unknown: 0.33 } },
      { probabilities: { first: 0.5, second: 0.5, third: 0.5 } },
      { probabilities: { first: 0.2, second: 0.4, third: 0.4 } },
      { choice: "unknown" },
      { confidence: 1.1 },
    ]) {
      const raw = choiceResponse();
      invalid.push({ ...raw, answers: { q: { ...raw.answers.q, ...change } } });
    }
    invalid.push({ ...choiceResponse(), answers: { extra: choiceResponse().answers.q } });
    invalid.push({ ...choiceResponse(), answers: { ...choiceResponse().answers, extra: choiceResponse().answers.q } });
    for (const raw of invalid) expect(() => adaptKevResponse(choiceRequest, raw)).toThrow("Invalid or mismatched");
  });

  test("rejects bad score arithmetic and unknown score keys at native precision", () => {
    const { request, response } = scorePair(["low", "medium", "high"], { "0": "low", "1": "medium", "2": "high" });
    if (response.answers.q?.type !== "score") throw new Error("Expected score");
    for (const change of [
      { score: 0.9 },
      { probabilities: { "0": 0.33, "1": 0.33, "3": 0.33 } },
      { legend: { "0": "low", "1": "medium", "3": "high" } },
      { probabilities: { "0": 0, "1": 0, "2": 0 } },
    ]) {
      const raw = { ...response, answers: { q: { ...response.answers.q, ...change } } };
      expect(() => adaptKevResponse(request, raw)).toThrow("Invalid or mismatched");
    }
  });

  test("rejects all-rounded-zero distributions even at the 255-option limit", () => {
    const criteria = Object.fromEntries(Array.from({ length: 255 }, (_, index) => [`option-${index}`, null]));
    const probabilities = Object.fromEntries(Object.keys(criteria).map((key) => [key, 0]));
    const request: SystemOneRequest = { state: null, questions: { q: { type: "choice", criteria } } };
    const response = { ...choiceResponse(), answers: { q: { type: "choice", choice: "option-0", probabilities, confidence: 0 } } };
    expect(() => adaptKevResponse(request, response)).toThrow("Invalid or mismatched");
    expect(() => validateResponseForRequest(request, response, 2)).toThrow("Invalid or mismatched");
  });

  test("requires a feasible normalized distribution within bounded rounding intervals", () => {
    const criteria = Object.fromEntries(Array.from({ length: 255 }, (_, index) => [`option-${index}`, null]));
    const request: SystemOneRequest = { state: null, questions: { q: { type: "choice", criteria } } };
    const makeResponse = (positiveCount: number): SystemOneResponse => ({
      ...choiceResponse(),
      answers: {
        q: {
          type: "choice",
          choice: "option-0",
          probabilities: Object.fromEntries(Object.keys(criteria).map((key, index) => [key, index < positiveCount ? 0.01 : 0])),
          confidence: 0,
        },
      },
    });
    // 200 probabilities of .005 can total one and each publish as .01.
    // Once 201 entries are .01, their lower bounds already exceed one.
    for (const positiveCount of [100, 200]) {
      const raw = makeResponse(positiveCount);
      expect(adaptKevResponse(request, raw)).toEqual(raw);
    }
    for (const positiveCount of [201, 220]) {
      expect(() => adaptKevResponse(request, makeResponse(positiveCount))).toThrow("Invalid or mismatched");
    }
  });

  test("bounds score rounding using a distribution that can still total one", () => {
    const criteria = Array.from({ length: 10 }, (_, index) => `level-${index}`);
    const request: SystemOneRequest = { state: null, questions: { q: { type: "score", criteria } } };
    const makeResponse = (winner: number, score: number): SystemOneResponse => ({
      ...choiceResponse(),
      answers: {
        q: {
          type: "score",
          score,
          legend: Object.fromEntries(criteria.map((entry, index) => [String(index), entry])),
          probabilities: Object.fromEntries(criteria.map((_, index) => [String(index), index === winner ? 1 : 0])),
          confidence: 1,
        },
      },
    });
    // .996 at one endpoint and .004 at the other publish as [1, 0, ...]
    // but retain a native score of .04 or 8.96. Larger gaps are impossible.
    for (const raw of [makeResponse(0, 0.04), makeResponse(9, 8.96)]) {
      expect(adaptKevResponse(request, raw)).toEqual(raw);
    }
    for (const raw of [makeResponse(0, 0.2), makeResponse(9, 8.8)]) {
      expect(() => adaptKevResponse(request, raw)).toThrow("Invalid or mismatched");
    }
    expect(() => validateResponseForRequest(request, makeResponse(0, 0.02))).toThrow("Invalid or mismatched");
    expect(validateResponseForRequest(request, makeResponse(0, 0.004))).toEqual(makeResponse(0, 0.004));
  });

  test("keeps three-decimal validation as the default and rejects unsupported precision at runtime", () => {
    const response = choiceResponse();
    if (response.answers.q?.type !== "choice") throw new Error("Expected choice");
    response.answers.q.probabilities = { first: 0.333, second: 0.333, third: 0.333 };
    expect(validateResponseForRequest(choiceRequest, response)).toEqual(response);
    for (const unsupported of [0, 1, 4, NaN, Infinity, null, "2"]) {
      expect(() => validateResponseForRequest(choiceRequest, response, unsupported as 2)).toThrow("Invalid or mismatched");
    }
  });
});
