#!/usr/bin/env bun
// Renders the launch beats, homepage mockups and social kit into the static
// site from one source: scripts/launch/{facts,beats,mockups}. Pages keep their
// hand-written HTML; only the text between the launch markers is generated.
//
//   bun scripts/launch/build.tsx --write   regenerate
//   bun scripts/launch/build.tsx --check   fail when a generated region is stale
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { assertLaunchBeats, assertLaunchKit, buildSocialKit, LAUNCH_LIMITS, type LaunchBeat, type SocialKit } from "@hraness/design-kit/launch";
import type { ReactElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { resolvedBeats } from "./beats.ts";
import { CANONICAL_URL, launchMessaging, launchRelease } from "./facts.ts";
import { LaunchMockup, type LaunchMockupId } from "./mockups.tsx";

const root = resolve(import.meta.dir, "../..");
const kitRoot = resolve(root, "node_modules/@hraness/design-kit");
const kitVersion = (JSON.parse(readFileSync(resolve(kitRoot, "package.json"), "utf8")) as { version: string }).version;

export const socialKit: SocialKit = buildSocialKit(resolvedBeats, launchMessaging, launchRelease, CANONICAL_URL);
assertLaunchKit(resolvedBeats, socialKit, {
  status: launchRelease.status,
  publicInstall: true,
  tagline: launchMessaging.tagline,
  canonicalUrl: CANONICAL_URL,
  forbiddenNames: ["gstack", "pstack", "Superpowers", "RTK"],
});

function VerificationStates(): ReactElement {
  return (
    <div className="launch-scorecard">
      <table>
        <caption>What verification results mean</caption>
        <thead><tr><th scope="col">State</th><th scope="col">Next step</th></tr></thead>
        <tbody>
          <tr><th scope="row">Confirmed</th><td>Read the evidence supporting the claim.</td></tr>
          <tr><th scope="row">Contradicted</th><td>Resolve the mismatch before reporting completion.</td></tr>
          <tr><th scope="row">Unverifiable</th><td>Collect the missing evidence.</td></tr>
        </tbody>
      </table>
    </div>
  );
}

function renderVisual(beat: LaunchBeat): ReactElement {
  switch (beat.visual.kind) {
    case "mockup":
      return <LaunchMockup id={beat.visual.id as LaunchMockupId} />;
    case "clip":
      return <img alt="" decoding="async" height={720} loading="lazy" src={`/media/launch/beat-${beat.id}.jpg`} width={1280} />;
    case "diagram":
      return <VerificationStates />;
  }
}

// Same structure as design-kit's <LaunchBeats> (react entry), which needs the
// private @hraness/ui peer; this public repository must build without it.
function launchBeatAnchor(beat: Pick<LaunchBeat, "id">): string {
  return `beat-${beat.id}`;
}

const figureKind = { mockup: "illustration", clip: "recording", diagram: "diagram" } as const;
function LaunchBeats({ beats }: Readonly<{ beats: readonly LaunchBeat[] }>): ReactElement {
  assertLaunchBeats(beats);
  return (
    <div className="launch-beats" data-hraness-launch-beats="">
      {beats.filter((beat) => beat.part === "does").map((beat) => {
        const anchor = launchBeatAnchor(beat);
        return (
          <section aria-labelledby={`${anchor}-heading`} className="launch-beat" data-part={beat.part} id={anchor} key={beat.id}>
            <h3 id={`${anchor}-heading`}>{beat.headline}</h3>
            <p>{beat.post}</p>
            <figure className="launch-beat-figure" data-figure-kind={figureKind[beat.visual.kind]}>
              <div className="launch-beat-visual">{renderVisual(beat)}</div>
            </figure>
            {beat.detailHref === undefined ? null : (
              <p className="launch-beat-detail"><a href={beat.detailHref}>{beat.id === "short-logs" ? "Use compact check output" : beat.id === "rules" ? "Set up code review" : "Set up completion checks"}</a></p>
            )}
          </section>
        );
      })}
    </div>
  );
}

function markup(element: ReactElement): string {
  const html = renderToStaticMarkup(element);
  // The site's CSP is style-src 'self'; inline style attributes would be dropped.
  if (/\sstyle="/u.test(html)) throw new Error("Generated launch markup must not carry inline styles.");
  return html;
}

function region(file: string, name: string, body: string): { path: string; next: string; current: string } {
  const path = resolve(root, file);
  const current = readFileSync(path, "utf8");
  const start = `<!-- launch:${name}:start (generated by scripts/launch/build.tsx) -->`;
  const end = `<!-- launch:${name}:end -->`;
  const from = current.indexOf(start);
  const to = current.indexOf(end);
  if (from < 0 || to < from) throw new Error(`${file} is missing the ${name} launch markers.`);
  return { path, current, next: `${current.slice(0, from + start.length)}\n${body}\n${current.slice(to)}` };
}

function kitMarkdown(kit: SocialKit): string {
  const thread = (title: string, posts: readonly string[], limit: number) =>
    [`## ${title}`, "", `Limit: ${limit} characters a post.`, "", ...posts.flatMap((post, index) => [`### ${index + 1} of ${posts.length}`, "", "```text", post, "```", ""])].join("\n");
  return [
    "# Sys1 launch social kit",
    "",
    "Generated by `bun scripts/launch/build.tsx --write` from `scripts/launch/beats.ts` and",
    "`scripts/launch/facts.ts`. Do not edit by hand; change the beats and regenerate.",
    `Canonical post: ${CANONICAL_URL}. Every post links to its section as \`#beat-<id>\`.`,
    "",
    thread("X", kit.x, LAUNCH_LIMITS.x),
    thread("Bluesky", kit.bluesky, LAUNCH_LIMITS.bluesky),
    thread("Threads", kit.threads, LAUNCH_LIMITS.threads),
    "## LinkedIn",
    "",
    "```text",
    kit.linkedin,
    "```",
    "",
    "## Product Hunt",
    "",
    `- Tagline: ${kit.productHunt.tagline}`,
    `- Tags: ${kit.productHunt.tags.join(", ")}`,
    "",
    "```text",
    kit.productHunt.description,
    "```",
    "",
    "## Fact sheet for Show HN and a first comment",
    "",
    "Write the Show HN post and first comment yourself; use only these facts.",
    "",
    ...kit.showHnFacts.map((fact) => `- ${fact}`),
    "",
    "## Media",
    "",
    "- Landscape film (52 s, captions): https://sys1.io/media/sys1-launch.mp4",
    "- Square cut for feeds: https://sys1.io/media/sys1-launch-square.mp4",
    "- Captions: https://sys1.io/media/sys1-launch.vtt",
    "",
    "## Sources",
    "",
    ...Object.entries(kit.sources).map(([key, source]) => `- \`${key}\`: ${source}`),
    "",
  ].join("\n");
}

const beatsHtml = markup(<LaunchBeats beats={resolvedBeats} />);

const homeHtml = markup(
  <div className="launch-home-mockups">
    <figure className="launch-home-figure"><LaunchMockup id="agent-review" /></figure>
    <figure className="launch-home-figure"><LaunchMockup id="verify" /></figure>
  </div>,
);

const mockupsCss = readFileSync(resolve(kitRoot, "src/mockups.css"), "utf8");
const provenance = `${JSON.stringify(
  {
    source: "@hraness/design-kit/mockups.css",
    version: kitVersion,
    sha256: createHash("sha256").update(mockupsCss).digest("hex"),
    note: "Unmodified copy. Regenerate with bun scripts/launch/build.tsx --write after a design-kit bump.",
  },
  null,
  2,
)}\n`;

const outputs: { path: string; current: string; next: string }[] = [
  region("site/introducing-sys1.html", "beats", `<h2 id="short-version">Put a check to work</h2><p class="launch-short-intro">Start with the part of your workflow that needs attention. Compact output runs locally; review and completion checks use your chosen model.</p>\n${beatsHtml}`),
  region("site/index.html", "mockups", homeHtml),
];
for (const [file, next] of [
  ["kb/launch/social-kit.md", kitMarkdown(socialKit)],
  ["site/vendor/hraness-mockups/mockups.css", mockupsCss],
  ["site/vendor/hraness-mockups/provenance.json", provenance],
] as const) {
  const path = resolve(root, file);
  let current = "";
  try {
    current = readFileSync(path, "utf8");
  } catch {}
  outputs.push({ path, current, next });
}

const mode = process.argv[2];
if (mode === "--write") {
  for (const output of outputs) if (output.current !== output.next) writeFileSync(output.path, output.next);
  console.log(`Launch assets written (${outputs.length} files).`);
} else if (mode === "--check") {
  const stale = outputs.filter((output) => output.current !== output.next).map((output) => output.path.slice(root.length + 1));
  if (stale.length > 0) {
    console.error(`Launch assets are stale: ${stale.join(", ")}. Run bun scripts/launch/build.tsx --write.`);
    process.exit(1);
  }
  console.log("Launch assets are current.");
} else if (import.meta.main) {
  console.error("Usage: bun scripts/launch/build.tsx --write|--check");
  process.exit(2);
}
